Vy/files launch from submissions page
BrightspaceHypermediaComponents/consistent-evaluation pull request #125
Opened 2020-10-21 19:29 UTC by vix633

When clicking on a file in assignment submissions, you are now taken to that file within CE

2020-10-21 19:48 UTC, vix633 commented
@max-hao-d2l FYI

2020-10-21 19:55 UTC, amauryperez commented on components/consistent-evaluation.js
> +			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
Verify that the acceptance of US121085 is still met

2020-10-21 19:57 UTC, AlexBedley commented on components/consistent-evaluation.js
> +			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
I think this change might flash the submissions-page during iteration. I'd check that

2020-10-21 20:00 UTC, vix633 commented on components/consistent-evaluation.js
> +			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
@max-hao-d2l This actually does break US121085 for us.

2020-10-21 20:07 UTC, vix633 commented
Merging master into this silently broke the functionality

2020-10-21 20:24 UTC, amauryperez commented on components/consistent-evaluation.js
>  			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
@max-hao-d2l maybe `resetEvidence` does not need to modify `userProgressOutcomeHref` and that will solve the issue?

2020-10-21 20:28 UTC, max-hao-d2l commented on components/consistent-evaluation.js
>  			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
I'll try it out

2020-10-21 20:36 UTC, max-hao-d2l commented on components/consistent-evaluation.js
>  			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
It seems to work. I'll put it on a separate PR

2020-10-21 20:37 UTC, amauryperez commented on components/consistent-evaluation.js
>  			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
cool, the idea of that method is for the left panel and that href has nothing to do with it.

2020-10-21 20:44 UTC, max-hao-d2l commented on components/consistent-evaluation.js
>  			this.shadowRoot.querySelector('d2l-consistent-evaluation-page')._resetEvidence();
So... I forgot to create a new branch and accidentally pushed to master. Huge oversight on my part, I won't do it again. Build has succeeded, though.

2020-10-22 14:02 UTC, vix633 commented
Huge thanks to @amauryperez for pointing out that we have a file-id attribute being set in the rendered already.

2020-10-22 16:15 UTC, AlexBedley requested changes

2020-10-22 16:15 UTC, AlexBedley commented on components/consistent-evaluation.js
> +				current-file-id=${ifDefined(this.fileId !== null && this.fileId)}
you can simplify this to just `ifDefined(this.fileId)` I think

2020-10-22 16:15 UTC, AlexBedley commented on components/consistent-evaluation.js
> +	_setFileIdFromUrl() {
Do we still need to do this if we're getting the `fileId` directly from props?

2020-10-22 16:15 UTC, AlexBedley commented on components/consistent-evaluation-page.js
> +		if (changedProperties.has('submissionInfo') && this.token) {
I am a bit worried about the trigger for this, it feels a bit fragile. For example, what if `submissionInfo` is set before `currentFileId`?

Additionally I would expect that changing `currentFileId` would be enough to change the current file to that one.

I think ideally `currentFileId` actually does control the current file. To make this happen, we just need to change right panel to accept fileId instead of `fileEvidenceUrl`. Then something lower down can figure out if that's text or file, and how to link `fileEvidenceUrl` and `fileId` (its just through the siren properties). This would really clean up page (we could delete like 3 properties) and make it much easier to reason about (in that world we just literally need to change `currentFileId` to change the current file).

2020-10-22 18:24 UTC, vix633 commented on components/consistent-evaluation-page.js
> +		if (changedProperties.has('submissionInfo') && this.token) {
I'd like to do this in a followup PR today or tomorrow. Rather than here.

2020-10-22 20:05 UTC, AlexBedley approved these changes
Looks good. Not a fan of us being responsible for nuking the query string. I'd prefer if the LMS did that, since it's the one that's reading from it. Not sure how feasible that would be though.

2020-10-22 20:12 UTC, merged