US121725 - Submissions - Evidence - Opening a submission does not mark the submission as read
BrightspaceHypermediaComponents/consistent-evaluation pull request #139
Opened 2020-10-27 12:15 UTC by amauryperez

2020-10-27 13:54 UTC, jmurray-d2l commented on components/header/d2l-consistent-evaluation-lcb-file-context.js
> +				this._submissionLateness = currentFile.properties.latenessTimespan;
is it worth checking for `currentFile.properties` ?

2020-10-27 13:55 UTC, jmurray-d2l commented on components/helpers/submissionsAndFilesHelpers.js
> +		const files = submission.entity.getSubEntityByRel(attachmentListRel).entities;
should we check for `getSubEntityByRel` return before accessing it's entities?

2020-10-27 14:01 UTC, amauryperez commented on components/header/d2l-consistent-evaluation-lcb-file-context.js
> +				this._submissionLateness = currentFile.properties.latenessTimespan;
dont we always have properties?

2020-10-27 15:16 UTC, jmurray-d2l approved these changes

2020-10-27 17:39 UTC, AlexBedley requested changes

2020-10-27 17:39 UTC, AlexBedley commented on components/helpers/submissionsAndFilesHelpers.js
> -		const files = getSubmissionFiles(submission);
`getSubmissionFiles` decorated the properties object and renamed a bunch of stuff (for better or worse, but that's another issue). Now that we're no longer using it, do we need to change consumers of this function in tandem?

For example, I don't think the `submissionLateness` property is actually from the file's `properties` it seems to be from the submission's properties

https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/blob/dfee293f1e32fefe6f66cd42444c4267c30766dc/components/helpers/submissionsAndFilesHelpers.js#L34

2020-10-27 17:39 UTC, AlexBedley commented on components/helpers/submissionsAndFilesHelpers.js
> +			continue;
were we seeing some bad data or is this just for safety?

2020-10-27 17:39 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-left-panel.js
> +		for (let i = 0; i < action.fields.length; i++) {
You can simplify this (and make it more clear we're just looking for a single field that fits the criteria) by using `some`

```js
if (action.fields.some(f => f.name === 'isRead' && f.value)) {
  performSirenAction(this.token, action, undefined, true);
}
```

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

2020-10-27 18:05 UTC, amauryperez commented on components/helpers/submissionsAndFilesHelpers.js
> -		const files = getSubmissionFiles(submission);
Interesting, I tested it and it works fine. Somehow that property is getting added, that is so weird

2020-10-27 18:06 UTC, amauryperez commented on components/helpers/submissionsAndFilesHelpers.js
> +			continue;
not bad data, I guess is just for safety. Do you think we don't need this check?

2020-10-27 18:16 UTC, amauryperez commented on components/helpers/submissionsAndFilesHelpers.js
> -		const files = getSubmissionFiles(submission);
Adding those extra properties seems a bit weird :-(

2020-10-27 19:44 UTC, AlexBedley commented on components/helpers/submissionsAndFilesHelpers.js
> +			continue;
On one hand if the data isn't the way we expect it might be better to know about it by failing loudly. But on the other hand we don't want to crash the entire application for a non-essential feature. We had a bit of a debate over this during the QE implementation and it was never really decided.

2020-10-27 19:45 UTC, AlexBedley commented on components/helpers/submissionsAndFilesHelpers.js
> -		const files = getSubmissionFiles(submission);
yeah I wonder if the entity store cache objects themselves are getting updated with these properties (if someone called `getSubmissionFiles` before you called `findFile`)

I do think adding those properties is a design smell. I would approve a PR to fix that after M1

2020-10-27 19:47 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-left-panel.js
> +			performSirenAction(this.token, action, undefined, true);
we should `await` this call

not a huge deal right now, but could be a problem if this function was modified.

2020-10-27 20:18 UTC, amauryperez commented on components/helpers/submissionsAndFilesHelpers.js
> -		const files = getSubmissionFiles(submission);
yeah, we should clean that for sure

2020-10-28 13:34 UTC, AlexBedley approved these changes

2020-10-28 13:36 UTC, merged