Jtran/nav bar
BrightspaceHypermediaComponents/consistent-evaluation pull request #81
Opened 2020-09-11 21:21 UTC by JamieTran

Apologies for the large PR but the nav-bar feature for consistent eval has been added.

The navbar contains the assignment name
The navbar contains the course name
The Navbar is hooked up to the iterator API (and iterates when you click)

Linked to story [US119994](https://rally1.rallydev.com/#/294005552584d/custom/236803223728?detail=%2Fuserstory%2F422977019400)

![image](https://user-images.githubusercontent.com/32204301/92973462-3f9d7200-f452-11ea-9b49-33291d288118.png)

An issue that came up with the addition of the iterator is that submissions are being appended to the submissions list and are not being cleared between students
![image](https://user-images.githubusercontent.com/32204301/92973910-103b3500-f453-11ea-928d-0924ca1b7070.png)

2020-09-11 21:25 UTC, JamieTran commented on components/controllers/ConsistentEvaluationHrefController.js
> +	async getIteratorTotal() {
I am not a fan of `getIteratorTotal() `and `getIteratorIndex()` being two different methods. I tried doing something like `getIteratorInfo()` and returning an object with both the `total` and the `index` but when it got down to the nav-bar component, I could not get the object to update with the correct values.

2020-09-11 21:29 UTC, JamieTran commented on components/header/consistent-evaluation-nav-bar.js
> +				back-link-href="https://www.d2l.com/"
The component is set up to take the return-href that @amauryperez has developed. It is a matter of passing it down through the multiple tiers and using it here.

2020-09-14 12:19 UTC, amauryperez commented
Isn't `package-lock.json` supposed to be excluded from PRs?

2020-09-14 12:35 UTC, amauryperez commented on components/consistent-evaluation-page.js
> +				<div slot="header">
In my local copy I can see `d2l-consistent-evaluation-learner-context-bar` inside the header slot, how come it is not here?

2020-09-14 13:19 UTC, JamieTran commented on components/consistent-evaluation-page.js
> +				<div slot="header">
I have not pulled master into my branch in a while, I will change this so it is up to date.

2020-09-14 13:39 UTC, amauryperez commented
Looks good to me. My only concern is the `package-lock.json` file, maybe @vix633 can confirm if it is ok to have it as part of the PR or if it should be excluded

2020-09-14 13:42 UTC, vix633 commented
> Looks good to me. My only concern is the `package-lock.json` file, maybe @vix633 can confirm if it is ok to have it as part of the PR or if it should be excluded

This is totally fine. It's not necessarily a part of the PR but we typically sneak an update of modules whenever we can.

2020-09-14 13:43 UTC, amauryperez commented
but isn't this particular file something that gets created locally when working on the repo? This is not `package.json` is the `lock` file

2020-09-14 13:46 UTC, vix633 commented
> but isn't this particular file something that gets created locally when working on the repo? This is not `package.json` is the `lock` file

This file is basically how we lock our dependencies to certain versions. When you delete this file and run `npm install` locally, it will create this file with new module versions if there are any based on what `package.json` specifies. Essentially, it prevents any automated installs from pulling any package versions that we didn't deliberately commit like Jamie is doing here.

2020-09-14 13:46 UTC, amauryperez approved these changes

2020-09-14 14:35 UTC, ChrisKraljevicD2L commented on components/consistent-evaluation.js
> +			this._iteratorIndex = await controller.getIteratorIndex();
Nit: can these controller `get` calls be `Promise.all`'d together? Seems like fetching these in parallel would net a performance gain. Unless they need to be `await`ed serially?

2020-09-14 14:35 UTC, ChrisKraljevicD2L commented on components/controllers/ConsistentEvaluationHrefController.js
> +	async getOrganizationName() {
This and `getAssignmentName` look very similar in terms of logic. Could the shared code and logic be put in its own function that accepts a parameter to differentiate between getting an assignment name and an organization name?

2020-09-14 14:35 UTC, ChrisKraljevicD2L commented on components/header/consistent-evaluation-nav-bar.js
> +				back-link-text="Back to D2L"
In case this isn't placeholder text, this string should be a langterm.

2020-09-14 14:35 UTC, ChrisKraljevicD2L commented on components/header/consistent-evaluation-nav-bar.js
> +					<span class="d2l-student-iterator d2l-label-text">User ${this.iteratorIndex} of ${this.iteratorTotal}</span>
langterm here too

2020-09-14 15:31 UTC, CodeBaboon commented on components/consistent-evaluation-page.js
> +						assignment-name=${this.assignmentName}
I think these properties should start with `.` (if nothing else to be consistent with https://github.com/BrightspaceHypermediaComponents/consistent-evaluation/pull/81/files#diff-c380577c4ac5f9e72316100b9a3a8a6eR85)

2020-09-14 15:34 UTC, amauryperez commented on components/header/consistent-evaluation-nav-bar.js
> +				back-link-text="Back to D2L"
In this case `back-link-text` should only be present if the respective property exist in the consistent-eval web component, if it does not exist then there is no need to set a default text value. Maybe don't add `back-link-text` and `back-link-href` as part of this PR

2020-09-14 15:36 UTC, CodeBaboon commented on components/consistent-evaluation.js
> +		this._organizationName = ' ';
Why are these defaulted to `' '`? Could the just be `undefined` or at least empty string?

2020-09-14 15:37 UTC, CodeBaboon commented on components/consistent-evaluation.js
> +		this.href = this._childHrefs.previousHref;
```suggestion
		this.href = this._childHrefs?.previousHref;
```
Suggest a `?` just in case `_childHrefs` were to be undefined.

2020-09-14 15:38 UTC, CodeBaboon commented on components/controllers/ConsistentEvaluationHrefController.js
> +		let assignmentName;
I don't think this variable is necessary. Instead you could just:

`return assignmentResponse.entity.properties.name;` on line 155, and `return undefined;` on line 159.

2020-09-14 15:44 UTC, CodeBaboon commented on components/controllers/ConsistentEvaluationHrefController.js
> +		return iteratorIndex;
Something to consider: if this ever returns `null` here will that cause problems with the `previous-disabled` logic in the nav bar?

2020-09-14 15:47 UTC, CodeBaboon commented
Probably this PR should update or add some unit tests.

2020-09-14 15:50 UTC, dbatiste commented on components/consistent-evaluation.js
> +		this._organizationName = ' ';
It is also unnecessary to assign `undefined` - the property values will already be undefined.  To avoid rendering "undefined" strings, use the `ifDefined` directive when necessary.

2020-09-14 15:52 UTC, dbatiste commented on demo/consistent-evaluation-nav-bar.html
> +		<title>d2l-consistent-evaluation-nav-bar</title>
It is not necessary to render a `<title>` element here.  The `d2l-demo-page` will automatically render the title element based on the value provided for `page-title`.

2020-09-14 16:21 UTC, JamieTran commented on components/consistent-evaluation.js
> +		this.href = this._childHrefs.previousHref;
Could this also apply to the `onNextStudentClick()` as well?

2020-09-14 16:21 UTC, JamieTran commented on components/controllers/ConsistentEvaluationHrefController.js
> +	async getOrganizationName() {
I totally agree, I applied the same fix to `getIteratorTotal()` & `getIteratorIndex()`

2020-09-14 16:22 UTC, JamieTran commented on components/header/consistent-evaluation-nav-bar.js
> +				back-link-text="Back to D2L"
You're correct, this is a placeholder text

2020-09-14 16:24 UTC, JamieTran commented on components/consistent-evaluation.js
> +		this._organizationName = ' ';
I didn't want the component to render in with the text 'undefined' before it was done fetching from the API. Will change to an empty string 😄 .

2020-09-14 16:26 UTC, dbatiste commented on components/consistent-evaluation.js
> +		this._organizationName = ' ';
Normally we would use `ifDefined` directive to avoid that.

2020-09-14 16:28 UTC, dbatiste commented on components/consistent-evaluation.js
> +	onPreviousStudentClick() {
Are these handlers meant to be private?  If so, they should be prefixed with a leading `_` for clarity.

2020-09-14 16:39 UTC, JamieTran commented on components/consistent-evaluation.js
> +	onPreviousStudentClick() {
updated 👍

2020-09-14 16:47 UTC, JamieTran commented on components/controllers/ConsistentEvaluationHrefController.js
> +		return iteratorIndex;
Good catch, the previous button remains enabled when the iteratorIndex is undefined (which we don't want). Fixed for `next-disabled` as well

2020-09-14 18:15 UTC, CodeBaboon requested changes
Code looks good now but still no tests.

2020-09-14 18:42 UTC, CodeBaboon approved these changes
I think this LGTM. Not sure if visual diff tests are required or not.

2020-09-14 19:15 UTC, dbatiste commented
I'm not sure what the state of visual-diff tests are in this repo, but in core we generally find that a few visual-diff tests provide far better coverage.  We generally only use the unit tests to cover what's not covered visually.

2020-09-15 13:27 UTC, merged