Fix submission list appending when iterating through students
BrightspaceHypermediaComponents/consistent-evaluation pull request #85
Opened 2020-09-21 15:07 UTC by JamieTran

Related to [US120545](https://rally1.rallydev.com/#/294005552584d/custom/236803223728?detail=%2Fuserstory%2F435781871716)

Fixed issue where iterating through students, all evidence for the students would append onto the submissions list. Did this by clearing the list of submissions when initializing the submission entity.

Also fixed a bug where the comments would not update.

![submission-list-fix](https://user-images.githubusercontent.com/32204301/93784123-96e1d600-fbfa-11ea-9b67-e99d1eeb3060.gif)

2020-09-22 13:37 UTC, vix633 approved these changes

2020-09-22 19:56 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submission-item.js
> +		this._comment = '';
what about resetting `this._attachments`?

This file might be simpler if you get rid of `submissionEntity` and  just pass `_comment` and `_attachments` from `consistent-evaluation-submissions-page.js` (it's already passing half of it's properties). That way this file doesn't need to know about hypermedia

2020-09-24 16:55 UTC, JamieTran commented on components/left-panel/consistent-evaluation-submission-item.js
> +		this._comment = '';
Oh I didnt notice attachments but that needs to be reset as well.
I also agree with simplifying `submission-item` by getting rid of `submissionEntity`

2020-09-24 18:39 UTC, AlexBedley requested changes

2020-09-24 18:39 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submission-item.js
> -		this._comment = '';
We might still want the defaults here (haven't been burned one way or the other yet, but for consistencies sake)

2020-09-24 18:39 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submission-item.js
> +		this._date = this.dateStr ? new Date(this.dateStr) : undefined;
`_date` probably doesn't need to exist anymore (at least as a class variable), it's only used in this function as far as I can tell

2020-09-24 18:39 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submissions-page.js
> +			_attachments: {
Similarly, these don't need to exist as lit properties, or even class properties. They're only used in scope of submission entity below. I would separate `_initializeSubmissionProperties` into `getComment(submissionEntity)` and `getAttachments(submissionEntity)` and just use the values locally in render

2020-09-24 19:11 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submission-item.js
> +		this.dateStr = this.dateStr ? new Date(this.dateStr) : undefined;
This won't work (I don't think the Date constructor can take a Date object the second time this function is called). Instead of re-using `this.dateStr` just make a local variable `date`. (also has the advantage of keeping `dateStr` a string)

2020-09-24 19:14 UTC, AlexBedley commented on components/left-panel/consistent-evaluation-submission-item.js
>  				type: Object
type should be `Array`

2020-09-24 19:21 UTC, AlexBedley approved these changes

2020-09-24 19:28 UTC, merged